### ISSUE TITLE
Developing a testing methodology

### ISSUE THREAD

**Issue by powerjg** [darchr/gem5#103]
Want a straightforward way to run experiments that is well documented.

**Comment by powerjg** [comment]
Ayaz has done a lot of this already. 

You can find the current progress in the base experiments repo?

Bradley used this for the FlexCPU experiments for ISPASS poster. 
@animalvgamer: Add in your what didn't work here.

# To do
[ ] Add GNU parallel to scripts
[ ] Document needed changes when running experiments

**Comment by animalvgamer** [comment]
The base experiments branch had a shell script which did a decent job of finding things to run and running them all, but did so all at once. It's not hard to modify the shell script though, but that seems to be the most straightforward way to adjust what needed to be run.

Using sem (parallel) was a pretty easy way to get around the all at once issue.

Microbenchmarks did need building which Ayaz did for me, but that did seem like an extra step between base experiments and getting workloads running.

Getting SPEC to work required some finagling with working directories, stdin/stdout, filenames, etc. which required decent amount of lines of python configuration unique to each workload. For SPEC CPU 2006 the Process configurations were ripped from the gem5 wiki, but I can see doing that becoming a pain for workloads that might not be available on the wiki.

**Comment by powerjg** [comment]
I'm going to close this since we're actively working on this in another repo: https://github.com/darchr/base-experiments
