### ISSUE TITLE
Revise the Resource system

### ISSUE THREAD

**Issue by animalvgamer** [darchr/gem5#131]
The Resource system is nonintuitive and has very strange behaviors, such as inconsistent latencies, etc. Needs a proper rewrite.

**Comment by powerjg** [comment]
It would be great if you included your sketch of a solution here. I'm
afraid the institutional knowledge here is going to be lost.
C

**Comment by animalvgamer** [comment]
A couple of thoughts:
- Latency to complete a request should be decoupled from latency to release the resource (allows for more reasonable zero-latency, finite bandwidth behavior)

- Ideally, we'd also slightly redesign the front-end so that future fetch/decode loops don't depend on issue loops, but could also be constrained independently so that we don't overfill buffers in aggressive front-end designs.

**Comment by animalvgamer** [comment]
This issue is also somewhat related to the goals of:
1) Modelling backpressure properly.
2) Specialized functional units.

A clean solution to this should be a good stepping stone toward those goals.
