### ISSUE TITLE
flags.isSet(STATIC_DATA|DYNAMIC_DATA) assertion

### ISSUE THREAD

**Issue by powerjg** [darchr/gem5#139]
This has come up a number of times on the mailing list. It needs to be fixed.

**Comment by powerjg** [comment]
I think this was fixed by @pfotouhi upstream. Can you confirm?

**Comment by pfotouhi** [comment]
@powerjg Yes, at least one cause that was happening frequently with O3 at FS. The change is [19449](https://gem5-review.googlesource.com/c/public/gem5/+/19449).
