### ISSUE TITLE
Wisconsin microbenchmarks

### ISSUE THREAD

**Issue by powerjg** [darchr/gem5#140]
Get these workloads into gem5.

https://github.com/VerticalResearchGroup/microbench

**Comment by powerjg** [comment]
[ ] Get working in gem5 with x86 + simple timing + simple memory
[ ] Get working with O3 CPU with simple memory
[ ] Extract the "right" stats for each microbenchmark
[ ] Get working with caches, etc.
[ ] Get working with RISC-V and ARM

Basically we want to have tests which only change one variable at a time.

No reason to use FS for these simple tests.

Finally, we want to be able to run these in the testing infrastructure.

**Comment by takekoputa** [comment]
The workloads are working with O3_W128 and O3_W2K from base-experiments. So the first two ticks are done?

**Comment by takekoputa** [comment]
The workloads seem to work with O3 ARM as well. I couldn't verify if I compiled the ARM binary correctly though.

**Comment by takekoputa** [comment]
So I picked the CCa workload, and printed out the variable t in the loop. The outputs are consistent across X86, ARM, and RISCV. I would say RISCV and ARM also work.

**Comment by powerjg** [comment]
See https://github.com/darchr/microbench/

**Comment by powerjg** [comment]
I think this issue is complete. The open items are better worked on in other issues (e.g., #63 #89)
