### ISSUE TITLE
FlexCPU visualizer

### ISSUE THREAD

**Issue by powerjg** [darchr/gem5#153]
Here's a thought. I'd like to see a visualization of this CPU. See the instructions in each of the queues and all of the instructions in the instruction window. I think this would be helpful in debugging.

This might be a good place to start with understanding the FlexCPU. It will also help debug the problems with it. I can draw what I'm thinking on the board next week.

- [x] Add method to print inflight inst (with color for state?)
- [x] Add method to thread to print all inflight insts in order
- [x] Come up with cool visualization
- [x] Add information about dependencies (maybe just a list)

This takes inspiration from the O3PipeView.
If you're really ambitious there's also this [GUI for it](https://github.com/shioyadan/Konata) that would be cool to replicate.

**Comment by powerjg** [comment]
Done?

**Comment by takekoputa** [comment]
there's a minor bug; I'm fixing it

**Comment by takekoputa** [comment]
Done.

**Comment by powerjg** [comment]
Mark this closed when you merge the PR #156 into flexcpu (#29)

**Comment by takekoputa** [comment]
Done!
