### ISSUE TITLE
Merge flexcpu thread constructors into one

### ISSUE THREAD

**Issue by powerjg** [darchr/gem5#154]
Add a boolean parameter, full_system and allow process to be null.

**Comment by takekoputa** [comment]
SimpleThread has 2 constructors: the full system constructor doesn't have `use_kernel_stat` but doesn't have `process`, while the SE constructor doesn't have `use_kernel_state`. I think it would be better to have two constructors to keep the flexcpu_thread constructors consistent with simple_thread's ones.

**Comment by powerjg** [comment]
Ok, fine :/. It's ugly, but I see what you're saying :).
