### ISSUE TITLE
Set up experiments and experimental design/methodology

### ISSUE THREAD

**Issue by powerjg** [darchr/gem5#74]

**Comment by powerjg** [comment]
@ayaz91, do you consider this done? If not, what's missing from it?

@animalvgamer, maybe you can use this to set up the experiments for testing store to load forwarding :).

**Comment by ayaz91** [comment]
Yeah, this is mostly done and can be used to run experiments.

**Comment by powerjg** [comment]
Should we close this then?

**Comment by ayaz91** [comment]
I think it can be closed now.
