### ISSUE TITLE
Double check everything works for memory and CPU tests

### ISSUE THREAD

**Issue by powerjg** [darchr/gem5#87]
Before pushing the CPU and memory tests, it would be good for someone else to test them (preferably not on amarillo).

To do this, go to the each changeset on gerrit and cherry pick it onto the "upstream" branch on darchr/gem5 or on master on gem5.googlesource.com.

## CPU tests
https://gem5-review.googlesource.com/c/public/gem5/+/15855
https://gem5-review.googlesource.com/c/public/gem5/+/15856
https://gem5-review.googlesource.com/c/public/gem5/+/15857

## Memory tests
https://gem5-review.googlesource.com/c/public/gem5/+/15835
https://gem5-review.googlesource.com/c/public/gem5/+/15836

Once you have run the tests and seen that they pass, you can give the review request a +2!

**Comment by powerjg** [comment]
Give a +2 to anything on gerrit that you've checked.

**Comment by powerjg** [comment]
@ayaz91 Any update on this? What was the issue that Rutuja found?

**Comment by ayaz91** [comment]
@powerjg The problem was related to the lack of compilation of MinorCPU by default in case of X86. I have removed the MinorCPU test for x86. I have validated the changes by applying these patches to clean upstream gem5 source code and tests seem to work fine for me. Maybe Rutuja can also verify.

**Comment by powerjg** [comment]
Great! Please do!

**Comment by powerjg** [comment]
I believe this is done. Let me know if I'm wrong.
